name: meetup
description: A new Flutter project.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  basic_utils: ^5.7.0
  cached_network_image: ^3.3.1
  change_app_package_name: ^1.5.0
  clipboard: ^0.1.3
  dartx: ^1.1.0
  dio: ^5.1.2
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  flag: ^7.0.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_downloader: ^1.11.7
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  google_mobile_ads: ^5.1.0
  google_nav_bar: ^5.0.6
  image_picker: ^1.1.2
  in_app_review: ^2.0.9
  jiffy: ^6.3.1
  line_icons: ^2.0.1
  localize_and_translate: ^4.1.1
  omni_jitsi_meet: ^1.0.1 
  onboarding_intro_screen: ^0.0.8
  package_info_plus: ^8.0.0
  pin_code_fields: ^8.0.1
  provider: ^6.0.3
  pull_to_refresh_flutter3: ^2.0.1
  quickalert: ^1.1.0
  random_string: ^2.3.1
  rename_app: ^1.6.2
  share_plus: ^11.0.0
  shared_preferences: ^2.0.15
  singleton: ^0.0.2
  stacked: ^3.4.0
  url_launcher: ^6.3.1
  url_launcher_ios: ^6.3.2
  velocity_x: ^4.3.1
  get_it: ^7.6.7
  google_generative_ai:
  emoji_picker_flutter: ^2.1.0
  loading_animation_widget: ^1.2.1
  mailer: ^6.1.0
  get: 4.6.6
  fluttertoast: ^8.0.9
  flutter_gemini: ^1.0.0
dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.2.3
  flutter_test:
    sdk: flutter

dependency_overrides:
  http: ^0.13.0
  translator: 0.1.7
  intl: ^0.19.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  image: assets/images/app_icon.png
  color: "20063B"

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lang/
    - assets/
